text = """
Nous avons entendu dans la parabole de l’Evangile que les vierges « sortirent à la rencontre de l’époux » (Mt 25, 1), toutes les dix. Pour chacun, la vie est un appel continuel à sortir : du sein de sa mère, de la maison où il est né, de l’enfance à la jeunesse, et de la jeunesse à l’âge adulte, jusqu’à la sortie de ce monde. Pour les ministres de l’Evangile également, la vie est une sortie continuelle : de la maison de famille à celle où l’Eglise nous envoie, d’un service à l’autre ; nous sommes toujours de passage, jusqu’au passage définitif.

L’Evangile rappelle le sens de cette sortie continuelle qu’est la vie : aller à la rencontre de l’époux. Voilà la raison de vivre : pour cette annonce qui, dans l’Evangile, résonne dans la nuit et que nous pourrons accueillir pleinement au moment de la mort : « Voici l’époux, sortez à sa rencontre ! » (v. 6). La rencontre avec Jésus, un Epoux qui « a aimé l’Eglise et s’est livré lui-même pour elle » (Ep 5, 25), donne sens et orientation à la vie. Rien d’autre. C’est la fin qui éclaire ce qui précède. Et de même que la semence se détermine en fonction la récolte, le chemin de la vie se trace à partir du but.

Alors, si la vie est un chemin en sortie vers l’époux, elle est le temps qui nous est donné pour grandir en amour. Vivre est une préparation quotidienne aux noces, de grandes fiançailles. Demandons-nous : est-ce que je vis comme quelqu’un qui prépare ma rencontre avec l’époux ? Dans le ministère, derrière toutes les rencontres, les activités à organiser et les dossiers à traiter, le fil qui unit toute la trame ne doit pas être oublié : l’attente de l’époux. Le centre ne peut qu’être un cœur qui aime le Seigneur. C’est seulement ainsi que le corps visible de notre ministère sera soutenu par une âme invisible. Nous comprenons alors ce que dit l’Apôtre Paul dans la seconde lecture : « Notre regard ne s’attache pas à ce qui se voit, mais à ce qui ne se voit pas ; ce qui se voit est provisoire, mais ce qui ne se voit pas est éternel » (2Co 4, 18). Nous ne nous fixons pas sur les dynamiques terrestres, nous regardons au-delà. Cette célèbre expression : « l’essentiel est invisible pour les yeux », est vraie. L’essentiel dans la vie c’est d’écouter la voix de l’époux. Elle nous invite à entrevoir chaque jour le Seigneur qui vient et à transformer toute activité en une préparation aux noces avec lui.

Dans l’Evangile, l’élément qui est essentiel pour les vierges en attente des noces nous le rappelle : non pas le vêtement, ni même les lampes, mais l’huile, conservée dans de petits vases. 

Une première caractéristique de cette huile apparaît : elle n’est pas voyante. Elle reste cachée, elle n’apparaît pas, mais sans elle, il n’y a pas de lumière. Qu’est-ce que cela nous suggère ? Que face au Seigneur les apparences ne comptent pas, c’est le cœur qui compte (cf. 1Sm 16, 7). Ce que le monde cherche et étale – les honneurs, la puissance, les apparences, la gloire – passe sans rien laisser. Prendre les distances par rapport aux apparences mondaines est indispensable pour se préparer au ciel. Il faut dire non à la “culture du maquillage” qui apprend à soigner les apparences. Le cœur doit, au contraire, être purifié et gardé, l’intérieur de l’homme, précieux aux yeux de Dieu ; non pas l’extérieur qui disparaît. 

Après cette première caractéristique – ne pas être voyante mais essentielle – il y a un autre aspect de l’huile : elle existe pour se consumer. Elle brille seulement en brûlant. Il en est de même pour la vie : elle répand la lumière seulement si elle se consume, si elle se dépense dans le service. Le secret pour vivre c’est de vivre pour servir. Le service est le billet à présenter à l’entrée des noces éternelles. Ce qui reste de la vie au seuil de l’éternité, ce n’est pas ce que nous avons gagné, mais ce que nous avons donné (cf. Mt 6, 19-21 ; 1Co 13, 8). Le sens de la vie c’est donner réponse à la proposition d’amour de Dieu. Et la réponse, elle passe à travers le véritable amour, le don de soi, le service. Servir coûte, car il signifie se dépenser, se consumer, mais dans notre ministère, celui qui ne vit pas pour servir ne sert pas à la vie. Celui qui garde trop sa vie, la perd.

Une troisième caractéristique de l’huile apparait de manière significative dans l’Evangile : la préparation. L’huile doit être préparée à temps et portée avec soi (cf. v. 7.7). L’amour, certes, est spontané, mais il ne s’improvise pas. C’est dans le manque de préparation que réside la sottise des vierges qui restent au dehors des noces. C’est maintenant le temps des préparatifs : l’amour doit être alimenté dans le moment présent, jour après jour. Demandons la grâce de renouveler chaque jour notre premier amour avec le Seigneur (cf. Ap 2, 4), de ne pas le laisser s’éteindre. La grande tentation est de s’aplatir dans une vie sans amour, qui est comme un vase vide, comme une lampe éteinte. Si l’on ne s’investit pas dans l’amour, la vie s’éteint. Les appelés aux noces avec Dieu ne peuvent pas se coucher dans une vie sédentaire, plate et horizontale, qui se poursuit sans élan, cherchant de petites satisfactions et courant après des reconnaissances éphémères. Une vie terne, de routine, qui se contente de faire son devoir sans se donner, n’est pas digne de l’Epoux.

Alors que nous prions pour les Cardinaux et les Evêques décédés dans le cours de l’année, demandons l’intercession de ceux qui ont vécu sans vouloir paraître, de ceux qui ont servi avec cœur, de ceux qui se sont préparés jour après jour à la rencontre avec le Seigneur. A l’exemple de ces témoins - grâce à Dieu il y en a, et nombreux – ne nous contentons pas d’un regard court sur l’aujourd’hui ; désirons au contraire un regard qui porte au-delà, aux noces qui nous attendent. Une vie traversée du désir de Dieu et formée à l’amour sera prête à entrer dans la demeure de l’Epoux, et ceci pour toujours."""