text = """
Regardons trois actions que Jésus accomplit dans l’Evangile.

La première. En plein jour, il laisse : il laisse la foule au moment du succès, quand il est acclamé pour avoir multiplié les pains. Et tandis que les disciples voulaient se réjouir de la gloire, il les oblige immédiatement à s’en aller et il renvoie la foule (cf. Mt 14,22-23). Recherché par les gens, il s’en va seul : lorsque tout était “en descente”, il monte sur la montagne pour prier. Puis, au cœur de la nuit, il descend de la montagne et rejoint les siens en marchant sur les eaux agitées par le vent. En tout, Jésus va à contre-courant : d’abord, il laisse le succès, puis la tranquillité. Il nous enseigne le courage de laisser : laisser le succès qui enfle le cœur et la tranquillité qui endort l’âme.

Pour aller où ? Vers Dieu, en priant, et vers celui qui a besoin, en aimant. Ce sont les vrais trésors de la vie : Dieu et le prochain. Monter vers Dieu et descendre vers les frères, voilà la route indiquée par Jésus. Il nous détourne de pâturer, sans être dérangés dans les plaines faciles de la vie, de vivoter oisivement au milieu des petites satisfactions quotidiennes. Les disciples de Jésus ne sont pas faits pour la tranquillité banale d’une vie normale. Comme le Seigneur Jésus, ils vivent leur chemin, légers, prêts à laisser les gloires du moment, attentifs à ne pas s’attacher aux biens qui passent. Le chrétien sait que sa patrie est ailleurs, il sait qu’il y est déjà – comme le rappelle l’apôtre Paul dans la seconde lecture – « concitoyens des saints, membres de la famille de Dieu » (cf. Ep 2,19). Il est un voyageur agile de l’existence. Nous ne vivons pas, nous, pour accumuler, notre gloire se trouve dans le fait de laisser ce qui passe pour retenir ce qui demeure. Demandons à Dieu de ressembler à l’Eglise décrite dans la première Lecture : toujours en mouvement, experte dans le détachement et fidèle dans le service (cf. Ac 28,11-14). Réveille-nous, Seigneur de l’oisiveté tranquille, du calme paisible de nos ports sûrs où nous sommes en sécurité. Détache-nous des amarres de l’autoréférentialité qui leste la vie, libère-nous de la recherche de nos succès. Enseigne-nous, Seigneur, à savoir laisser pour fonder la route de notre vie sur la tienne : vers Dieu et vers le prochain.

La seconde action : en pleine nuit, Jésus encourage. Il va vers les siens, plongés dans l’obscurité, en marchant « sur la mer » (v. 25). En réalité, il s’agissait d’un lac, mais la mer, avec la profondeur de ses obscurités souterraines, évoquait à cette époque les forces du mal. Jésus, en d’autres paroles, va à la rencontre des siens en piétinant les ennemis mauvais de l’homme. Voilà la signification de ce signe : ce n’est pas une manifestation célébrant la puissance, mais la révélation pour nous de la rassurante certitude que Jésus, seulement Lui, Jésus, vainc nos grands ennemis : le diable, le péché, la mort, la peur, la mondanité. A nous aussi aujourd’hui, il dit : « Confiance ! c’est moi, n’ayez plus peur » (v.27).

La barque de notre vie est souvent ballottée par les flots et secouée par les vents, et lorsque les eaux sont calmes elles recommencent vite à s’agiter. Alors nous nous en prenons aux tempêtes du moment, qui semblent nos uniques problèmes. Mais le problème n’est pas la tempête du moment, c’est la manière de naviguer dans la vie. Le secret pour bien naviguer est d’inviter Jésus à bord. Le gouvernail de la vie lui est donné, afin que ce soit Lui qui conduise la route. Lui seul en effet donne vie dans la mort et espérance dans la douleur ; Lui seul guérit le cœur par le pardon et libère de la peur par la confiance. Aujourd’hui, invitons Jésus dans la barque de notre vie. Comme les disciples, nous ferons l’expérience qu’avec Lui à bord, les vents se calment (cf. v.31) et on ne fait jamais naufrage. Avec Lui à bord, on ne fait jamais naufrage ! Et c’est seulement avec Jésus que nous devenons capables nous aussi d’encourager. Il y a un grand besoin de gens qui sachent consoler, non pas avec des paroles vides, mais bien avec des paroles de vie, avec des gestes de vie. Au nom de Jésus on donne une consolation véritable. Ce ne sont pas des encouragements formels et limités, mais c’est la présence de Jésus qui redonne des forces. Encourage-nous, Seigneur : consolés par toi, nous serons de vrais consolateurs pour les autres.

Et troisième action de Jésus : au milieu de la tempête, il tend la main (cf. v.31). Il saisit Pierre qui, apeuré, doutait et, en s’enfonçant, criait : « Seigneur, sauve-moi ! ». Nous pouvons nous mettre à la place de Pierre : nous sommes des gens de peu de foi et nous sommes ici pour mendier le salut. Nous sommes des pauvres de vraie vie et nous avons besoin de la main tendue du Seigneur, qui nous tire hors du mal. C’est le début de la foi : se vider de l’orgueilleuse conviction de nous croire en ordre, capables, autonomes, et reconnaître que nous avons besoin de salut. La foi croît dans ce climat, un climat auquel on s’habitue en se tenant avec tous ceux qui ne se mettent pas sur un piédestal, mais qui ont besoin et demandent de l’aide. Pour cela, vivre la foi au contact de ceux qui ont besoin est important pour nous tous. Ce n’est pas une option sociologique, ce n’est pas la mode d’un pontificat, c’est une exigence théologique. C’est nous reconnaître mendiants de salut, frères et sœurs de tous, mais spécialement des pauvres, les préférés du Seigneur. Ainsi nous atteignons l’esprit de l’Evangile : « l’esprit de pauvreté et de charité – dit le Concile – est, en effet, la gloire et le témoignage de l’Eglise du Christ » (Const. Gaudium et spes, n. 88).

Jésus a entendu le cri de Pierre. Demandons la grâce d’entendre le cri de celui qui vit dans des eaux tumultueuses. Le cri des pauvres : c’est le cri étranglé des enfants qui ne peuvent naître, des petits qui souffrent de la faim, des enfants habitués au fracas des bombes au lieu des cris joyeux des jeux. C’est le cri des personnes âgées mises de côté et laissées seules. C’est le cri de celui qui se trouve à affronter les tempêtes de la vie sans une présence amie. C’est le cri de celui qui doit fuir, laissant sa maison et sa terre sans la certitude d’un but. C’est le cri de populations entières, privées même des ressources naturelles considérables dont ils disposent. C’est le cri des nombreux Lazare qui pleurent, tandis qu’une poignée de riches fait des banquets avec ce qui, en justice, revient à tous. L’injustice est la racine perverse de la pauvreté. Le cri des pauvres devient chaque jour plus fort, mais chaque jour moins écouté. Chaque jour ce cri est plus fort, mais chaque jour moins écouté, dominé par le vacarme de quelques riches, qui sont toujours moins nombreux et toujours plus riches.

Devant la dignité humaine piétinée, souvent on reste les bras croisés ou on ouvre les bras, impuissants face à la force obscure du mal. Mais le chrétien ne peut rester les bras croisés, indifférent, ou les bras ouverts, fataliste, non. Le croyant tend la main, comme fait Jésus avec lui. Auprès de Dieu le cri des pauvres trouve une écoute. Je demande : et en nous ? Avons-nous des yeux pour voir, des oreilles pour entendre, des mains tendues pour aider, ou bien répétons-nous ce “reviens demain” ? « Le Christ lui-même, dans la personne des pauvres, en appelle comme à haute voix à la charité de ses disciples » (ibid.). Il nous demande de le reconnaître dans celui qui a faim et soif, qui est étranger et dépouillé de sa dignité, malade et en prison (cf. Mt 25,35-36).

Le Seigneur tend la main : c’est un geste gratuit, ce n’est pas un dû. C’est ainsi qu’on fait. Nous ne sommes pas appelés à faire le bien seulement à celui qui nous aime. Echanger est normal, mais Jésus nous demande d’aller au-delà (cf. Mt 5,46) : de donner à celui qui ne peut pas rendre, c’est-à-dire d’aimer gratuitement (cf. Lc 6,32-36). Regardons nos journées : parmi les nombreuses choses, faisons-nous quelque chose de gratuit, quelque chose pour celui qui n’a rien à donner en échange ? Ce sera notre main tendue, notre véritable richesse au ciel.

Tends-nous la main, Seigneur, saisis-nous. Aide-nous à aimer comme tu aimes, toi. Enseigne-nous à laisser ce qui passe, à encourager celui qui se trouve à côté de nous, à donner gratuitement à celui qui est dans le besoin. Amen."""