texts = ["""
Chers frères et sœurs, bonjour!

L’Evangile de ce dimanche (cf. Mc 10, 2-16) nous offre la parole de Jésus sur le mariage. Le récit commence par la provocation des pharisiens qui demandent à Jésus s’il est licite pour un mari de répudier sa femme, comme le prévoyait la loi de Moïse (cf. vv. 2- 4). Tout d’abord, Jésus, avec la sagesse et l’autorité qui lui viennent du Père, redimensionne la prescription mosaïque en disant: «C’est en raison de votre dureté de cœur qu’il — c’est-à-dire l’ancien législateur — a écrit pour vous cette prescription» (v. 5). Autrement dit, il s’agit d’une concession servant à atténuer les failles produites par notre égoïsme, mais elle ne correspond pas à l’intention originelle du Créateur.

Et ici, Jésus reprend le livre de la Genèse: «Mais dès l’origine de la création Il [Dieu] les fit homme et femme. Ainsi donc l’homme quittera son père et sa mère, et les deux ne feront qu’une seule chair» (vv. 6-7). Et il conclut: «Eh bien! Ce que Dieu a uni, l’homme ne doit point le séparer» (v. 9). Dans le projet originel du Créateur, il n’y a pas d’homme qui épouse une femme puis, si les choses ne marchent pas, qui la répudie. Non. Au contraire, il y a l’homme et la femme appelés à se reconnaître, à se compléter, à s’aider mutuellement dans le mariage.

Cet enseignement de Jésus est très clair et défend la dignité du mariage, en tant qu’union d’amour qui implique la fidélité. Ce qui permet aux couples mariés de rester unis dans le mariage, c’est un amour qui est don réciproque, soutenu par la grâce du Christ. Si, en revanche, l’intérêt individuel et la satisfaction personnelle prévalent chez les époux, leur union ne pourra pas résister.

Et c’est la même page évangélique qui nous rappelle avec beaucoup de réalisme que l’homme et la femme, appelés à vivre l’expérience de la relation et de l’amour, peuvent douloureusement faire des gestes qui provoquent une crise. Jésus n’admet pas tout ce qui peut conduire au naufrage de la relation. Il le fait pour confirmer le dessein de Dieu, dans lequel ressortent la force et la beauté de la relation humaine. L’Eglise, d’une part, ne se lasse pas de confirmer la beauté de la famille telle qu’elle nous a été transmise par l’Ecriture et par la Tradition; dans le même temps, elle s’efforce de faire ressentir concrètement sa proximité maternelle à ceux qui vivent l’expérience de relations brisées ou qui sont poursuivies avec souffrance et difficulté.

La manière dont Dieu agit avec son peuple infidèle — c’est-à-dire avec nous — nous enseigne que l’amour blessé peut être guéri par Dieu, grâce à la miséricorde et au pardon. Par conséquent, dans ces situations, il n’est pas seulement demandé à l’Eglise de condamner immédiatement. Au contraire, face à tant d’échecs conjugaux douloureux, elle se sent appelée à vivre sa présence d’amour, de charité et de miséricorde, pour ramener à Dieu les cœurs blessés et perdus.

Invoquons la Vierge Marie pour qu’elle aide les époux à vivre et à renouveler toujours leur union, à partir du don originel de Dieu.


A l’issue de l’Angélus

Chers frères et sœurs! Aujourd’hui, fête de la Vierge du Rosaire, j’adresse un salut spécial aux fidèles rassemblés au sanctuaire de Pompéi pour la supplique traditionnelle, présidée en cette occasion par le cardinal Mario Zenari, nonce apostolique en Syrie. Je renouvelle à tous mon invitation à prier le Rosaire chaque jour du mois d’octobre, en concluant par l’antienne «Sous ta protection» et la prière à saint Michel Archange, pour repousser les attaques du diable qui veut diviser l’Eglise.

Samedi prochain aura lieu à Rome la première journée des catacombes. Beaucoup de sites seront ouverts au public, avec des ateliers pédagogiques et des manifestations culturelles. Je remercie la Commission pontificale d’archéologie sacrée pour cette initiative et je souhaite à celle-ci mes meilleurs vœux de réussite.

Je vous salue tous avec affection, romains et pèlerins, en particulier les familles et les groupes paroissiaux venant d’Italie et de diverses parties du monde. Je salue les étudiants de Neuilly (France).

Je souhaite à tous un bon dimanche. S’il vous plaît, n’oubliez pas de prier pour moi. Bon déjeuner et au revoir!

""", """Chers frères et sœurs, bonjour!

La page de l’Evangile d’aujourd’hui (cf. Mc 10, 35-45) décrit Jésus qui, encore une fois et avec une grande patience, cherche à corriger ses disciples en les convertissant de la mentalité du monde à celle de Dieu. L’occasion lui en est donnée par les frères Jacques et Jean, deux des premiers que Jésus a rencontrés et appelés à le suivre. Désormais, ils ont parcouru un long chemin avec lui et ils appartiennent précisément au groupe des douze apôtres. C’est pourquoi, alors qu’ils sont en chemin vers Jérusalem, où les disciples espèrent avec impatience que Jésus, à l’occasion de Pâques, instaurera finalement le Royaume de Dieu, les deux frères s’arment de courage, s’approchent et adressent leur requête au Maître: «Accorde-nous de siéger, l’un à ta droite et l’autre à ta gauche, dans ta gloire» (v. 37).

Jésus sait que Jacques et Jean sont animés par un grand enthousiasme pour Lui et pour la cause du Royaume, mais il sait également que leurs attentes et leur zèle sont entachés par l’esprit du monde. C’est pourquoi il répond: «Vous ne savez pas ce que vous demandez» (v. 38). Et tandis qu’ils parlaient de «trônes de gloire» sur lesquels s’asseoir à côté du Christ Roi, Lui parlait d’une «coupe» à boire, d’un «baptême» à recevoir, c’est-à-dire de sa passion et de sa mort. Jacques et Jean, visant toujours le privilège espéré, disent de façon impulsive: oui, «nous pouvons»! Mais même ici, ils ne se rendent pas vraiment compte de ce qu’ils disent. Jésus annonce qu’ils boiront sa coupe et qu’ils recevront son baptême, c’est-à-dire qu’eux aussi, comme les autres apôtres, participeront à sa croix, quand leur heure viendra. Cependant — conclut Jésus — «quant à siéger à ma droite ou à ma gauche, il ne m’appartient pas de l’accorder, mais c’est pour ceux à qui cela a été destiné» (v. 40). Cela revient à dire: à présent suivez-moi et apprenez le chemin de l’amour «à perte», et c’est le Père céleste qui pensera à la récompense. La voie de l’amour est toujours «à perte», parce qu’aimer signifie mettre de côté l’égoïsme, l’autoréférentialité, pour servir les autres. 

Jésus réalise ensuite que les dix autres apôtres sont en colère contre Jacques et Jean, montrant ainsi qu’ils ont la même mentalité mondaine. Et cela lui offre l’occasion d’une leçon qui vaut pour les chrétiens de tous les temps, également pour nous. Il dit: «Vous savez que ceux qu’on regarde comme les chefs des nations dominent sur elles en maîtres et que les grands leur font sentir leur pouvoir. Il ne doit pas en être ainsi parmi vous: au contraire, celui qui voudra devenir grand parmi vous, sera votre serviteur, et celui qui voudra être le premier parmi vous, sera l’esclave de tous» (v. 42-44). C’est la règle du chrétien. Le message du Maître est clair: alors que les grands de la Terre se construisent des «trônes» pour leur pouvoir, Dieu choisit un trône inconfortable, la croix, de laquelle il règne en donnant la vie: «Le Fils de l’homme — dit Jésus — n’est pas venu pour être servi, mais pour servir et donner sa vie en rançon pour une multitude» (v. 45).

La voie du service est l’antidote le plus efficace contre la maladie de la recherche des premières places; c’est le remède pour les carriéristes, cette recherche des premières places, qui contamine tant de contextes humains et n’épargne pas même les chrétiens, le peuple de Dieu, ni même la hiérarchie ecclésiastique. C’est pourquoi, en tant que disciples du Christ, accueillons cet Evangile comme un appel à la conversion, afin de témoigner avec courage et générosité d’une Eglise qui s’incline aux pieds des derniers, pour les servir avec amour et simplicité. Que la Vierge Marie, qui a adhéré pleinement et humblement à la volonté de Dieu, nous aide à suivre Jésus avec joie sur le chemin du service, la voie royale qui mène au ciel.


A l’issue de l’Angélus

Chers frères et sœurs, hier à Malaga (Espagne), a été proclamé bienheureux le prêtre jésuite Tiburcio Arnáiz Muñoz (1865-1926), fondateur des Missionnaires des doctrines rurales. Rendons grâce au Seigneur pour le témoignage de ce ministre zélé de la réconciliation et annonciateur inlassable de l’Evangile, en particulier parmi les humbles et les oubliés. Que son exemple nous pousse à être des agents de miséricorde et des missionnaires courageux dans tous les milieux; que son intercession soutienne notre chemin. Un applaudissement pour le bienheureux Tiburcio, tous ensemble!

Nous célébrons aujourd’hui la journée mondiale des missions, sur le thème «Avec les jeunes, portons l’Evangile à tous». Avec les jeunes: voilà le chemin! Et c’est la réalité que, grâce à Dieu, nous vivons ces jours-ci au cours du synode qui leur est consacré: en les écoutant et en les faisant participer, nous découvrons de nombreux témoignages de jeunes qui ont trouvé en Jésus le sens et la joie de la vie. Et souvent, ils l’ont rencontré grâce à d’autres jeunes, appartenant déjà à sa compagnie de frères et sœurs qu’est l’Eglise. Je pense aux nombreux chrétiens, hommes et femmes, laïcs, consacrés, prêtres, évêques, qui ont consacré leur vie et la consacrent encore loin de leur patrie, pour annoncer l’Evangile. A eux s’adressent notre amour, notre gratitude et notre prière. Récitons pour eux un «Je vous salue Marie»...

Je vous salue à présent tous, pèlerins provenant d’Italie et de divers pays. En particulier ceux du lycée «Saint-Chaumond» de Poitiers. 

J’adresse une pensée spéciale au groupe de la Caritas Internationalis, guidé par le président, le cardinal Luís Antonio Tagle, avec des évêques et des personnes provenant de divers pays du monde. Vous avez accompli un bref pèlerinage à Rome, pour exprimer le désir de marcher ensemble en apprenant ainsi à mieux vous connaître. J’encourage cette initiative de «partager le chemin», qui est promue dans de nombreuses villes et qui peut transformer notre rapport avec les migrants. Merci beaucoup à la Caritas!

Et je souhaite à tous un bon dimanche. S’il vous plaît, n’oubliez pas de prier pour moi. Bon déjeuner et au revoir."""]